name: expense_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3
  sqflite: ^2.3.0
  flutter_sms_inbox: ^1.0.3
  permission_handler: ^11.1.0
  provider: ^6.1.1
  intl: ^0.19.0
  fl_chart: ^0.66.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/Open_Sans/static/OpenSans-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/static/Montserrat-Medium.ttf
          
  uses-material-design: true


flutter_launcher_icons:
  android: true
  ios: true
  # "Icon made by Pixel perfect from www.flaticon.com"
  # Source: https://www.flaticon.com/free-icon/budget_781760?term=expense&page=1&position=5&origin=search&related_id=781760
  image_path: "assets/icon/icon.png" 
