name: expense_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3
  sqflite: ^2.3.0
  flutter_sms_inbox: ^1.0.3
  permission_handler: ^11.1.0
  provider: ^6.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway/static/Raleway-Regular.ttf
        - asset: fonts/Raleway/static/Raleway-Italic.ttf
          style: italic

    - family: RobotoMono
      fonts:
        - asset: fonts/Roboto_Mono/static/RobotoMono-Regular.ttf
        - asset: fonts/Roboto_Mono/static/RobotoMono-Bold.ttf
          weight: 700

    - family: OpenSans
      fonts:
        - asset: fonts/Open_Sans/static/OpenSans-Regular.ttf
          
  uses-material-design: true
